uwblueprint/headsupguys

pages/api/models/module.ts, pages/api/models/slide.ts, pages/api/models/tool.ts
[API Routes Module](https://www.notion.so/uwblueprintexecs/API-Routes-Module-351fe0c5308d4a0fae54968bb0a7fe5e)
* Builds API routes for the Module table
1.  Investigate the module.ts file and try writing some mongoose tests in the dbTest file if you would like
* Ensuring that the module.ts file follows best practice (https://mongoosejs.com/docs/schematypes.html) and works as intended
=> [DB Schema] Create Module Model

pages/api/models/component.ts
[Database Models](https://www.notion.so/uwblueprintexecs/Task-Board-485f846ae00243599dddba2be9bcba82?p=6ee1bd0f594340a4914b2a165696ee1f)
* create models folder
* create model for component
1.
*
=> [DB Schema] Create Component Model

pages/api/models/tool.ts
[Database Models](https://www.notion.so/uwblueprintexecs/Task-Board-485f846ae00243599dddba2be9bcba82?p=6ee1bd0f594340a4914b2a165696ee1f)
* create model for tool
1.
*
=> [DB Schema] Create Tool Model

pages/api/models/selfCheckGroup.ts, pages/api/models/selfCheckQuestion.ts
[API Routes (Self Check Group)](https://www.notion.so/uwblueprintexecs/API-Routes-Self-Check-Group-60d04719da5241a2ad9b6818f5cccf42)
* Builds API routes for the Self Check Question and Self Check Group
1. Analyze selfCheckQuestion.ts and selfCheckGroup.ts files
* Ensuring that the selfCheckQuestion.ts and selfCheckGroup.ts files follow best practice (https://mongoosejs.com/docs/schematypes.html) and work as intended
=> [DB Schema] Create Self Check Model

pages/api/models/component.ts, pages/api/models/slide.ts
[API Routes (Slide)](https://www.notion.so/uwblueprintexecs/da60bba45b0d434d964125f89ea73d93?v=a7d2d46a50ea4a5593223b242eb39957&p=106d6eaaae5c4c46bd9e349d25025442)
* Adds slide model schema and types
1. Try creating a document and persisting it to the database
*
=> [DB Schema] Create Slide Model

database/models/selfCheckQuestion.ts, pages/api/self-check-question/[id].ts, pages/api/self-check-question/get.ts, pages/api/self-check/[id].ts, pages/api/self-check/delete.ts, pages/api/self-check/get.ts, pages/api/self-check/index.ts, pages/api/self-check/patch.ts, pages/api/self-check/post.ts
[API Routes (Self Check Group)](https://www.notion.so/uwblueprintexecs/API-Routes-Self-Check-Group-60d04719da5241a2ad9b6818f5cccf42)
* Base routes for the Self Check Group (GET, PATCH, DELETE)
1.
* Consistency across routes
* Correct implementation + route naming
=> Self check group api routes

pages/api/tool/[id].ts, pages/api/tool/create.ts, pages/api/tool/deleteOne.ts, pages/api/tool/getAll.ts, pages/api/tool/getOne.ts, pages/api/tool/index.ts, pages/api/tool/post.ts, pages/api/tool/update.ts
[API Routes (Tool)](https://www.notion.so/uwblueprintexecs/Task-Board-485f846ae00243599dddba2be9bcba82?p=744ad877c0264383a4c547204c8037d7)
* created functions for each of the endpoints on [Notion](https://www.notion.so/uwblueprintexecs/API-Routes-eeb9e4403fba4676922868228329016b)
* dynamic routes in `[id].js`
* regular routes in `index.js`
1. make requests to the endpoints
*
=> Tool API Routes

src/components/modal/index.tsx
* modal had some out-of-date errors that need to be fixed
* removed the <><> that wrapped around ChakraModal
* added support for `...rest`
* make header text prop optional
1.
*
=> fix errors with modal

src/components/index.ts, src/components/modulePreview/index.tsx, src/definitions/chakra/theme/components/button.ts
[Module Builder - Preview Screen](https://www.notion.so/uwblueprintexecs/Preview-Screen-9c29f26880e84f2d94f9edaa9b60deeb)
* Preview screen for module builder, mobile and desktop versions
* Props to determine buttons, button text, and progress, takes all preview content as children
* Print/save buttons disappear when false, prev/next buttons disable when false
* Modified progress bar styling
1. Ensure consistent with mockups and that all functionality is included
**Usage**
Set props and pass in any content as children
**Desktop**
Note: must scroll to see buttons when content overflows
**Mobile**
Note: buttons fixed to bottom when content doesn't overflow
* Styling may need updates
=> [Module Builder] - Preview Screen

src/components/toolHomePage/index.tsx
[Ticket Name](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)
* 
1.
*
=> Small linting change

pages/admin/dashboard/builder.tsx, pages/admin/dashboard/modules.tsx, src/components/ModuleCard/index.tsx, yarn.lock
[[Module Builder] Saving and naming a Module](https://www.notion.so/uwblueprintexecs/Module-Builder-Saving-and-naming-a-Module-07351349115b40ebb475a255b6434e05)
* Navigation from module card to builder page for a module
* Builder page creates new module when name is saved
* Update existing module in builder page with PATCH
1. Run app locally + connect to database
2. Go to `/admin/dashboard/modules`
3. Click create new module to go to `/admin/dashboard/builder`
4. Enter a name (should give you an error if not provided) and save, the **moduleId should append to the url**
5. Check that the new module shows up in `/admin/dashboard/modules`
6. Click on the card to make sure it redirects to `/admin/dashboard/builder?moduleId=______`
* Modules are correctly saving to database and can be accessed …
=> [Module Builder] Saving and naming a Module

pages/protected-admin.tsx, pages/protected.tsx, src/utils/auth/authHelpers.ts
[Admin login](https://www.notion.so/uwblueprintexecs/Auth-Implement-Admin-login-674f2796f8e74abca16e6642fb7b4e64): the ticket doesn't have any info, but the goal was to extract authentication logic into a separate hook and implement role based authentication (admin-permission pages)
* Added an additional custom attribute to the user pool on AWS Cognito called role (access as `custom:role`)
* Currently, the only role is "admin". Regular users will not have any `custom:role` attribute if you view them in Cognito
* Logic for checking if a user is authenticated and getting user props in a protected page is extracted to a helper `isAuthenticated(req, res, requiresAdmin)` that can be called in `getServerSideProps`.
* Basic admin auth: If `requiresAdmin` param in `isAuthenticated` is true, the …
=> Authentication Hook and Admin Login

pages/admin/dashboard/toolBuilder.tsx, pages/api/tool/post.ts, pages/api/tool/update.ts
[Ticket Name](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)
Goal of task is to update tool post/patch so that when you link a tool to a module in the Tool Builder, the link is also reflected on the module model.
This also integrates Chinemerem's unmerged changes from the tool builder to update the saving toast to only pop up if saving is successful. I also added an error toast if errors are encountered in saving.
* Updated POST/PATCH API routes for tool to also update the module when linking a tool and module together. If the selected module does not exist or is already linked to a tool, it returns an error
* Updated toasts on tool builder uses Chinemerem's changes and added an error toast with a generic error message
1. Create/edit a tool using the …
=> Update module when linking tool with module

pages/admin/dashboard/builder.tsx, src/components/moduleSectionSelect/index.tsx, src/pages/module-builder/Editor.tsx
[Ticket Name](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)
* 
1.
*
=> MD-Editor-Deletion-Bugs

database/models/section.ts, database/scripts/seed.ts, pages/admin/dashboard/builder.tsx, src/components/index.ts, src/components/moduleSectionSelect/index.tsx, src/components/multiSelect/index.tsx, src/components/multipleChoice/index.tsx, src/pages/module-builder/Document.tsx, src/pages/module-builder/Editor.tsx
[[Module Builder] Multiple Choice/Multi select](https://www.notion.so/uwblueprintexecs/Module-Builder-Multiple-Choice-Multi-select-3294b253658c4981ba7ece96635386f2)
- Created new section props for `multipleChoice` and `multiSelect` to store question + options
- Components for both section types, functionality to add options
- Sending data to Redux upon editing to be updated in database upon `Save`
- Created preview components that show up in `ModulePreview`, containing question and options as they are added
- Single and double column displays (test manually for now)
1. Create a new module
3. Add a `Multiple Choice` or `Multi-Select` section - edit the question and add options
4. Save the module and ensure the section just added is populated with the correct data
- Functionality: you can …
=> [Module Builder] Multiple Choice & Multiselect

pages/admin/dashboard/builder.tsx, src/components/modulePreview/index.tsx, src/pages/module-builder/Document.tsx, src/pages/module-builder/Header.tsx, src/pages/module-builder/Toolbar.tsx
[Ticket Name](https://www.notion.so/uwblueprintexecs/Module-Builder-Misc-Improvements-7d91d1d00b6e48e6b138c71a1fb6a3dc)
* removed 0 in place of Progress Bar
* made discard clear current changes
* save and discard states
* move user to new slide when it is created
1. Go through the 4 sub tickets on the notion and ensure this pr addresses the expected issues
* Functionality works as expected
* No bugs encountered related to this pr
=> Module builder misc bugs

pages/index.tsx
[[Toolkit Landing Page] Toolkit landing page fetches data from backend](https://www.notion.so/uwblueprintexecs/Toolkit-Landing-Page-Toolkit-landing-page-fetches-data-from-backend-12c599dd77804afdb9b2d451830beec4)
* Used `useSWR` to fetch data from backend
* Mapped data to `UserToolCard` components
* Followed original styling
* Used `useRouter` to route `UserToolCard` button clicks
1. Go to `http://localhost:3000/`
2. Observe that tool cards are displayed with data from the backend; main page content should look something like this:
3. Click on a continue learning button
4. Observe redirect to `http://localhost:3000/tool?id=<_id>` (note that page does not exist)
5. Go to `http://localhost:3000/`
6. Click on a self check button
7. Observe redirect to …
=> [Toolkit Landing Page] Fetch data from backend on toolkit landing page

pages/admin/dashboard/tools.tsx, pages/index.tsx, src/pages/module-builder/Toolbar.tsx
[Correctly Identify Linked Module on Tool Card](https://www.notion.so/uwblueprintexecs/Tool-Builder-Correctly-Identify-Linked-Module-9fa8847462894532b1bf39f6008dc107)
Merge/review #72 first if you're here and it's still open
* Properly does boolean to determine whether a tool is linked to a module
1. Visit `admin/dashboard/tools` and see if the tools properly identify linked modules
* Correct Tool Cards
=> Correctly Identify Linked Module on Tool Card

database/models/section.ts, database/scripts/seed.ts, pages/admin/dashboard/builder.tsx, pages/api/aggregations/addPaddingTypeToSectionPadding.ts, src/components/moduleSectionSelect/index.tsx, src/pages/module-builder/Document.tsx
* Implements percent based padding option
* Just play around with it and see if u like it
blocked by #69
=> Percentage based padding

database/models/section.ts, database/scripts/seed.ts, pages/admin/dashboard/builder.tsx, pages/module/[module].tsx, src/components/index.ts, src/components/moduleSectionSelect/index.tsx, src/components/shortAnswer/index.tsx, src/pages/module-builder/Document.tsx
[[Module Builder] Short Answer](https://www.notion.so/uwblueprintexecs/Module-Builder-Short-Answer-1a1a3f4784d84ea29f40e78a1952a720)
* Made Short Answer Module Builder Section
1. Add short answer module builder section
2. Play around with values and ensure no new bugs are discovered
3. Look through the changed files on github and ensure no major coding qualms are present
* Module builder short answer section
=> Add MD builder short answer

pages/admin/dashboard/builder.tsx, pages/admin/dashboard/modules.tsx, pages/api/module/[id].ts, pages/api/module/del.ts, src/components/ModuleCard/index.tsx, src/components/moduleSectionSelect/index.tsx, src/components/multiSelect/index.tsx, src/components/multipleChoice/index.tsx, src/pages/module-builder/Editor.tsx
[\[Module Builder\] Enable deletion](https://www.notion.so/uwblueprintexecs/Module-Builder-Enable-deletion-ccae551e87fa4d22a036cc0a0ab6a509)
* Implemented module deletion, but did not test properly linked modules (not sure how to link modules and the prelinked ones from seeding don't work properly for me)
* Implemented section deletion
* Implemented subcomponent deletion for multiple choice and multiselect but not short answer (we can't add multiple short answer fields yet)
1. Go to `http://localhost:3000/admin/dashboard/modules`
2. Create a module
3. Add some sections (e.g. 4 sections)
4. Select some content types (e.g. one of each)
5. Delete some options for multiple choice and multiselect sections
6. Delete some sections (observe the confirmation modal)
7. Test steps 3-6 in different …
=> [Module Builder] Enable deletion

pages/api/aggregations/addPaddingTypeToSectionPadding.ts, pages/api/module/[id].ts, pages/api/module/[id]/slide/[sid].ts, pages/api/module/[id]/slide/index.ts, pages/api/module/del.ts, pages/api/module/get.ts, pages/api/module/getAll.ts, pages/api/module/patch.ts, pages/api/module/post.ts, pages/api/self-check/[id].ts, pages/api/self-check/delete.ts, pages/api/self-check/get.ts, pages/api/self-check/patch.ts, pages/api/self-check/post.ts, pages/api/slide/[id].ts, pages/api/slide/delete.ts, pages/api/slide/get.ts, pages/api/slide/patch.ts, pages/api/slide/post.ts, pages/api/tool/deleteOne.ts, pages/api/tool/getAll.ts, pages/api/tool/getOne.ts, pages/api/tool/post.ts, pages/api/tool/update.ts
[Ticket Name](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)
* Call connectDB before every api function
=> Fix: API calls not working on startup

pages/admin/dashboard/toolBuilder.tsx
[[Tool Builder] Resolve Bugs](https://www.notion.so/uwblueprintexecs/Tool-Builder-Resolve-Bugs-34a528a36db746b7aa6d2ded9b9c3a43)
1. Add many self check questions to module self check
2.  Type into fields and change question types at random
3. Change related tools rapidly
4. Quickly Change question type
5. **Save the tool** and ensure no errors occur
6. Repeat steps 1 - 5 in random orders and ensure that no bugs are encountered
* Module persistence bugs
=> Fix Tool Builder Bugs

pages/module/[module].tsx, src/components/markdownRenderer/index.tsx, src/components/markdownRenderer/markdown-renderer.module.css, src/components/modulePreview/index.tsx, src/components/moduleSectionSelect/index.tsx, src/components/multiSelect/index.tsx, src/components/multipleChoice/index.tsx, src/components/shortAnswer/index.tsx, src/pages/module-builder/Document.tsx
[[Module Experience] Breakpoints](https://www.notion.so/uwblueprintexecs/Module-Experience-Breakpoints-f5c6b0b1e8114b218f4e9724796b026c)
* Fixed the responsive design for the /module/[moduleID] page
* Allowed interaction with the module/[moduleID] page
1. Make a module and take note it it's generated ID in the url (after saving)
2. Navigate to localhost::3000/module/moduleID
3. Ensure that the module looks like it did in the preview
4. Ensure that you can check any multiplechoice/multiselect boxes, and write in any appropriate text fields in the moduleID page but not on the module creation page
5. Check for any new bugs on the module creation and module viewing pages and tell @ChinemeremChigbo if any are found 
* The module interaction page
=> [Module Experience] Breakpoints

database/models/progress.ts, pages/api/progress/[id].ts, pages/api/progress/get.ts, pages/api/progress/patch.ts, pages/api/progress/post.ts
[\[Auth\] Add user progress tracking - backend](https://www.notion.so/uwblueprintexecs/Auth-Add-user-progress-tracking-backend-e3efe0890b0b488d800ecca45298bb04)
* Added `progress` model (see ticket for details)
* Added progress REST APIs
1. Open `/pages/index.tsx`
2. Replace the following code (line 195):
```
const Home: React.FC = () => {
const [showAlert, setShowAlert] = useState(true);
const [user, setUser] = useState<any | null>(null);
const variant = useMediaQuery({ query: `(max-width: 925px)` })
? "mobile"
: "desktop";
useEffect(() => {
const getCurrentUser = async () => {
const currentUser = await Auth.currentAuthenticatedUser();
setUser(currentUser);
};
getCurrentUser().catch(console.error);
}, []);
return (
<>
```
With this:
```
const Home: React.FC = () => {
const [showAlert, …
```
=> [Auth] Add user progress tracking - backend

pages/admin/dashboard/toolBuilder.tsx, src/components/index.ts, src/components/toolSelfCheckResponse/index.tsx
[[Tool Builder] Self Check Response](https://www.notion.so/uwblueprintexecs/Task-Board-485f846ae00243599dddba2be9bcba82?p=eefac0f1739049ce92abbf45673b9f6b)
* Used array of breakpoints
* Each breakpoint has a component attached to it
* The component is created using the data from the breakpoint data in the array
* Creates the new breakpoint by setting the lower as the last breakpoint's upper + 1
1. Open http://localhost:3000/admin/dashboard/tools
2. Create or edit an existing tool
3. Go to Self Check tab
4. Click Response
5. Explore! You can try to add new breakpoints, change the screen size, set the min and max of the breakpoints, add questions, etc. Note that you will have to create questions for the self check that are either multiple choice or multiselect to be able to play around with …
=> Tool Builder - Self Check Responses (FRONT-END)
